##===- projects/ise/lib/common/Makefile -----------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
LEVEL=../..

#
# Give the name of a library.  This will build a dynamic version.
#
LIBRARYNAME=dot_common

# BOOST graph library wants exception handling
REQUIRES_EH=1

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common
