##===- projects/sample/lib/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#

# DIRS = dot_common dotBB test
DIRS = dot_common dotBB


include $(LEVEL)/Makefile.common
